### ISSUE TITLE
Close "feature" branch

### ISSUE THREAD

**Issue by unknwnc** [zachdyer/pong#10]
It doesn't not look like you have done anything with the 'feature' branch; can we close it to avoid confusion?

Also, now that I have access to this repo, can we both develop on branches on it?
I can delete my fork, and start working on the assets loader in a branch.

**Comment by spaced-out-factory** [comment]
Ok I'll delete the feature branch. And Yes you can do that. But what am I gonna work on. I can't think of anything besides mobile stuff I guess.
